# Generated by Django 4.2.1 on 2023-10-30 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Event',
            new_name='User',
        ),
    ]
