# Generated by Django 4.2.1 on 2023-10-30 09:55

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barcode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(default='', upload_to=main.models.image_upload_path)),
            ],
        ),
    ]
