# Generated by Django 4.2.1 on 2023-11-03 17:43

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_profile_event_image_alter_barcode_writers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barcode',
            old_name='writers',
            new_name='writer',
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='', null=True, upload_to=main.models.image_upload_path),
        ),
    ]
