# Generated by Django 4.2.1 on 2023-12-01 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_barcode_image_myproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myproduct',
            name='price',
        ),
    ]
